// ============================================================
// TAZA AI SERVICE — FRONTEND CONSTANTS
// These values intentionally mirror the existing AI service.
// DO NOT add unsupported produce types here.
// ============================================================


// ------------------------------------------------------------
// Supported Produce
// Backend AI service currently supports ONLY these:
// apple, banana, orange
// ------------------------------------------------------------

export const PRODUCE_TYPES = [
  "Apple",
  "Banana",
  "Orange",
];


// ------------------------------------------------------------
// Storage Types
// Must match StorageType enum in the AI service.
// ------------------------------------------------------------

export const STORAGE_TYPES = [
  {
    value: "cold_storage",
    label: "Cold Storage",
  },
  {
    value: "ambient",
    label: "Ambient Storage",
  },
  {
    value: "controlled_atmosphere",
    label: "Controlled Atmosphere",
  },
  {
    value: "refrigerated_transport",
    label: "Refrigerated Transport",
  },
  {
    value: "unknown",
    label: "Unknown",
  },
];


// ------------------------------------------------------------
// Decision Engine Actions
//
// These are generated by the AI decision engine.
// ------------------------------------------------------------

export const ACTIONS = {
  SELL: "Sell locally",
  DISCOUNT: "Discount now",
  REDISTRIBUTE: "Ship to high-demand location",
  RESCUE: "Redirect to processing",
};


// ------------------------------------------------------------
// AI Risk Levels
// ------------------------------------------------------------

export const RISK_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  UNKNOWN: "UNKNOWN",
};


// ------------------------------------------------------------
// AI Urgency
// ------------------------------------------------------------

export const URGENCY_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  UNKNOWN: "UNKNOWN",
};


// ------------------------------------------------------------
// Batch Conditions
// ------------------------------------------------------------

export const BATCH_CONDITIONS = {
  GOOD: "GOOD",
  MIXED: "MIXED",
  POOR: "POOR",
};


// ------------------------------------------------------------
// Data Quality
// ------------------------------------------------------------

export const DATA_QUALITY = {
  GOOD: "GOOD",
  PARTIAL: "PARTIAL",
  INSUFFICIENT: "INSUFFICIENT",
};


// ------------------------------------------------------------
// Analysis Form Configuration
//
// These fields correspond directly to the existing
// /analyze-batch AI endpoint.
// ------------------------------------------------------------

export const ANALYSIS_FIELDS = {
  batchId: {
    name: "batch_id",
    label: "Batch ID",
    type: "text",
    required: true,
  },

  produce: {
    name: "produce",
    label: "Produce",
    type: "select",
    required: true,
  },

  quantityKg: {
    name: "quantity_kg",
    label: "Batch Quantity",
    type: "number",
    unit: "kg",
    min: 0,
    required: true,
  },

  images: {
    name: "images",
    label: "Produce Images",
    type: "file",
    accept: "image/*",
    multiple: true,
    required: true,
  },

  harvestAgeDays: {
    name: "harvest_age_days",
    label: "Harvest Age",
    type: "number",
    unit: "days",
    min: 0,
    max: 365,
  },

  temperatureC: {
    name: "temperature_c",
    label: "Storage Temperature",
    type: "number",
    unit: "°C",
    min: -30,
    max: 60,
  },

  humidityPercent: {
    name: "humidity_percent",
    label: "Humidity",
    type: "number",
    unit: "%",
    min: 0,
    max: 100,
  },

  storageDurationHours: {
    name: "storage_duration_hours",
    label: "Storage Duration",
    type: "number",
    unit: "hours",
    min: 0,
    max: 8760,
  },

  transportDurationHours: {
    name: "transport_duration_hours",
    label: "Transport Duration",
    type: "number",
    unit: "hours",
    min: 0,
    max: 2000,
  },

  storageType: {
    name: "storage_type",
    label: "Storage Type",
    type: "select",
  },
};


// ------------------------------------------------------------
// Navigation
//
// Recommendations is removed because recommendations are
// already produced by the Layer 3 decision engine.
// ------------------------------------------------------------

export const NAV_ITEMS = [
  {
    labelKey: "nav.dashboard",
    path: "/",
    icon: "LayoutDashboard",
  },

  {
    labelKey: "nav.inspect",
    path: "/analyze",
    icon: "ScanLine",
  },

  {
    labelKey: "nav.batches",
    path: "/batches",
    icon: "Boxes",
  },

  {
    labelKey: "nav.traceability",
    path: "/traceability",
    icon: "QrCode",
  },

  {
    labelKey: "nav.agent",
    path: "/agent",
    icon: "Sparkles",
  },
];


// ------------------------------------------------------------
// Market input
//
// Used by Layer 3 decision engine.
// ------------------------------------------------------------

export const MARKET_FIELDS = {
  location: {
    name: "location",
    label: "Market Location",
    type: "text",
    required: true,
  },

  demandKg: {
    name: "demand_kg",
    label: "Demand",
    type: "number",
    unit: "kg",
    min: 0,
    required: true,
  },

  pricePerKg: {
    name: "price_per_kg",
    label: "Price",
    type: "number",
    unit: "₹/kg",
    min: 0,
    required: true,
  },
};


// ------------------------------------------------------------
// Route input
//
// Used by Layer 3 decision engine to determine whether
// redistribution is feasible within the shelf-life window.
// ------------------------------------------------------------

export const ROUTE_FIELDS = {
  destination: {
    name: "destination",
    label: "Destination",
    type: "text",
    required: true,
  },

  transportHours: {
    name: "transport_hours",
    label: "Transport Time",
    type: "number",
    unit: "hours",
    min: 0,
    required: true,
  },

  transportCost: {
    name: "transport_cost",
    label: "Transport Cost",
    type: "number",
    unit: "₹",
    min: 0,
    required: true,
  },
};


// ------------------------------------------------------------
// Image upload constraints
// ------------------------------------------------------------

export const IMAGE_CONFIG = {
  accept: "image/*",
  multiple: true,
  minFiles: 1,
};


// ------------------------------------------------------------
// Default analysis form
// ------------------------------------------------------------

export const DEFAULT_ANALYSIS_FORM = {
  batchId: "",
  produce: "",
  quantityKg: "",

  images: [],

  harvestAgeDays: "",
  temperatureC: "",
  humidityPercent: "",

  storageDurationHours: "",
  transportDurationHours: "",

  storageType: "",

  markets: [],
  routes: [],

  localMarket: null,
};